version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
      - "25:2525"
    env_file:
      - .env.backend
    volumes:
      - ./Backend/DataBase:/app/DataBase
    restart: unless-stopped

  frontend:
    build:
      context: .                 # теперь контекст = корень вашего репо
      dockerfile: Frontend/Dockerfile
    env_file:
      - .env.frontend            # подтягиваем переменные в рантайм (необязательно, но по аналогии)
    ports:
      - "5042:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
