version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
      - "25:2525"
    env_file:
      - .env.backend
    volumes:
      - ./Backend/DataBase:/app/DataBase
    restart: unless-stopped

  nginx:                        # или как вы привыкли называть свой фронт‑сервис
    build:
      context: ./Frontend       # контекст — папка с вашим фронтендом и его Dockerfile
      dockerfile: Dockerfile
    env_file:
      - .env.frontend           # подтягиваем переменные для Vite
    ports:
      - "5042:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
