version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
      - "25:2525"
    env_file:
      - .env
    volumes:
      - ./Backend/DataBase:/app/DataBase
    restart: unless-stopped

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data: