version: "3.9"

services:
  backend:
    build: ./Backend
    env_file: .env.backend          # файл будет лежать рядом, но в .gitignore
    volumes:
      - db_data:/app/DataBase       # SQLite вне контейнера
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      args:
        VITE_BACKEND_URL: /api      # то, что React увидит в fetch'ах
    restart: unless-stopped

  nginx:
    image: nginx:1.27-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5042:80"                   # кривые порты наружу
      - "5443:443"
    depends_on: [backend, frontend]
    restart: unless-stopped

volumes:
  db_data:
