version: "3.9"

services:
  backend:
    build: ./Backend
    ports:
      - "5050:5050"
      - "25:2525"
    env_file:
      - .env.backend
    volumes:
      - ./Backend/DataBase:/app/DataBase
    restart: unless-stopped

  nginx:                     # контейнер с фронтом
    build:
      context: .             # весь репозиторий
      dockerfile: ./nginx/Dockerfile
    env_file:                # (как у бэка) прокидываем .env внутрь рантайма
      - .env.frontend
    ports:
      - "5042:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  db_data:
