name: Deploy-via-SCP

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync code to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host:      ${{ secrets.SSH_HOST }}
          username:  ${{ secrets.SSH_USER }}
          key:       ${{ secrets.SSH_KEY }}
          port:      ${{ secrets.SSH_PORT || 22 }}
          source:    "./"               # весь репозиторий
          target:    "/opt/mail"        # куда на сервере

      - name: Docker деплой на сервере
        uses: appleboy/ssh-action@v1.2.2
        with:
          host:     ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key:      ${{ secrets.SSH_KEY }}
          port:     ${{ secrets.SSH_PORT || 22 }}
          script: |
            cd /opt/mail
            docker-compose down -v --remove-orphans
            docker-compose up -d --build --no-cache
            docker image prune -f
