name: Simple-SSH-Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Скачиваем репозиторий
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Копируем файлы на сервер
      - name: Sync code to server via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          source: "./"
          target: "/opt/mail"
          strip_components: 1
          recursive: true
          exclude: |
            .git/
            *.db

      # 3) Перезапускаем контейнеры
      - name: Run docker-compose on server
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            cd /opt/mail
            # Проверяем наличие .env файлов на сервере
            if [ ! -f .env.backend ]; then
              echo "Error: .env.backend not found on server"
              exit 1
            fi
            if [ ! -f .env.frontend ]; then
              echo "Error: .env.frontend not found on server"
              exit 1
            fi
            # Выводим содержимое .env файлов для отладки (без секретных данных)
            echo "Contents of .env.backend:"
            grep -Ev 'SECRET|KEY' .env.backend || true
            echo "Contents of .env.frontend:"
            grep -Ev 'SECRET|KEY' .env.frontend || true
            # Экспортируем переменные
            export $(grep -Ev '^\s*(#|$)' .env.backend | xargs)
            export $(grep -Ev '^\s*(#|$)' .env.frontend | xargs)
            docker-compose down --remove-orphans
            docker-compose up -d --build --no-cache
            docker image prune -f