name: Simple-SSH-Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            cd /opt/mail

            # 1) Гарантируем чистый репозиторий
            git fetch --all
            git reset --hard origin/main
            git clean -fd

            # 2) Пересобираем контейнеры без кэша
            docker compose down --remove-orphans
            docker compose up -d --build --no-cache

            # 3) Убираем dangling-образы
            docker image prune -f

            # 4) Сбрасываем кеш Cloudflare
            curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE }}/purge_cache" \
              -H "Authorization: Bearer ${{ secrets.CF_TOKEN }}" \
              -H "Content-Type: application/json" \
              --data '{"purge_everything":true}'
