- name: Deploy over SSH
  uses: appleboy/ssh-action@v1.2.2
  with:
    host: ${{ secrets.SSH_HOST }}
    username: ${{ secrets.SSH_USER }}
    key: ${{ secrets.SSH_KEY }}
    script: |
      set -e
      cd /opt/mail
      
      # — свежий код
      git fetch --all
      git reset --hard origin/main
      git clean -fd
      
      # — пересобираем без кеша
      docker-compose down -v --remove-orphans
      docker-compose up -d --build --no-cache
      
      # — чистим Cloudflare-кэш
      CF_TOKEN="${{ secrets.CF_TOKEN }}"
      CF_ZONE="${{ secrets.CF_ZONE }}"
      curl -X POST "https://api.cloudflare.com/client/v4/zones/${CF_ZONE}/purge_cache" \
        -H "Authorization: Bearer ${CF_TOKEN}" \
        -H "Content-Type: application/json" \
        --data '{"purge_everything":true}'
      
      # — убираем dangling образы
      docker image prune -f
